### ISSUE TITLE
Documentation: What is the difference between templates and template?

### ISSUE THREAD

**Issue by hgoebl** [jonschlinkert/templates#3]
I'm a quite heavy user of assemble. Maybe there is no reason to change something in assemble, but the project seems to be sleeping for a while and for that reason I was looking for the next big thing in static site generation. I encountered templates and template and they appear to be very similar, not just their names.

Could you please provide some information which project to use, depending on the case?

And I'm asking myself how much value assemble provides compared to templates. Is it much more than a grunt-plugin calling template and selecting a template engine (handlebars)?

Where would templates be used? Typically "offline" site generation or delivering "online", embedded in something like express?

I apologize if the questions are dumb, maybe I'm not deep enough in that business and as a result not able to imagine what to do with the more low-level libraries you provide. BTW thanks for your great work!

**Comment by jonschlinkert** [comment]
> I apologize if the questions are dumb

these are all good questions, no worries at all. I'll start with the heading..

> What is the difference between templates and template? 

it's nothing complicated. I'm in the process of fixing some things I think I did wrong before. We just received the name `templates`, so we're moving `template` over to `templates`. Then we're going to use `templates` in assemble and refactor `template` to be mostly what's in [this file](https://github.com/jonschlinkert/templates/blob/master/lib/view.js). After that's done, `templates` will use `template` to handle the `View` class.

Bottom line, the names will be more semantically correct:
- `templates` manages template collections
- `template` is (will be) a single template

> but the project (assemble) seems to be sleeping for a while and for that reason I was looking for the next big thing in static site generation.

If you take a look at assemble's branches, `dev` specifically, there have been 725 commits to assemble since the last minor version change. https://github.com/assemble/assemble/pull/767

> Is it much more than a grunt-plugin calling template and selecting a template engine (handlebars)?

As of 0.6, Assemble is a 100% standalone library. No longer a grunt plugin, but we will continue to provide support for grunt with [grunt-assemble](https://github.com/assemble/grunt-assemble). 

> how much value assemble provides compared to templates. 

Value is in the eye of the beholder :) but I'll try to sum up the major differences:

**Templates**

Main purpose: Template collections and rendering
- creates views
- creates and manages custom view collections
- engine selection
- routes
- compiling and rendering

`templates` expects you to read and write your own files. There is no concept of src, dest, tasks etc.

**Assemble**

Main purpose: Building projects (static sites, rapid prototyping)
- manages and runs `tasks`
- `src`, `dest` and `copy`, for reading and writing files
- adds higher level processing to simplify site generation and rapid prototyping, like automatically calculating relative paths for dest files

> I was looking for the next big thing in static site generation

Keep watching the `dev` branch on Assemble :) we're about to release some things that will be game changing. 

Does this help?

**Comment by jonschlinkert** [comment]
btw I'll be sure to get these things clarified on the docs of all related libs as well. I think it will be more obvious when it's all done.

**Comment by hgoebl** [comment]
Thnx @jonschlinkert, this really helps and I'm looking forward to see assemble 0.6.
Do you think it's already time to give it a try for a small "pilot" project?
I could migrate one of my static sites or start one of my "backlog" site projects...
Would not be a problem when changes occur later :fearful:

**Comment by jonschlinkert** [comment]
> Do you think it's already time to give it a try for a small "pilot" project?

yeah, I think if you use the `dev` branch it should be okay. Docs are in progress though, so you might need to figure things out until then. We don't anticipate any major API changes happening on 0.6, just bug fixes

**Comment by hgoebl** [comment]
Thanks again, I'll give it a try soon.
